### ISSUE TITLE
请问为什么登不进去

### ISSUE THREAD

**Issue by ZiheHuang1** [doublechaintech/his-biz-suite#2]
是不是账号密码修改了呀

**Comment by philipgreat** [comment]
重新试试看呢

https://demo.doublechaintech.com/admin/his/
13900000001/admin123

**Comment by ShoneKey** [comment]
请问这个项目运行的数据库是定制的么

**Comment by philipgreat** [comment]
标准的Posgres和MySQL，没有定制。

**Comment by philipgreat** [comment]
MySQL和Postgres都可以用
